### ISSUE TITLE
Add a module to convert key to slot using CRC16_LOOKUP

### ISSUE THREAD

**Issue by nitinstp23** [nitinstp23/redix-cluster#4]
Ref - 

- https://redis.io/topics/cluster-spec#appendix
- https://github.com/redis/redis-rb/blob/master/lib/redis/cluster/key_slot_converter.rb

**Comment by mourjo** [comment]
Hey I have started working on this, notifying here to avoid duplicate work, thanks! 👍

**Comment by mourjo** [comment]
TODO: Support predictable hashes when keys have braces https://redis.com/blog/redis-clustering-best-practices-with-keys/

While it is possible for many keys to be in the same hash slot, this is unpredictable from a key naming standpoint and it’s not sane to constantly check the slot (with `CLUSTER KEYSLOT` in open source or Enterprise in Cluster API mode) when naming keys. The best way to approach this is with some advanced planning and a feature called hash tags. In open source Redis, curly braces (`{` and `}`) are signifiers of a hash tag and the string between these two characters is put through the CRC16 hashing function. Let’s take a look at a few examples:

Key | Hashing Pseudocode | Hash Slot
-- | -- | --
user-profile:1234 | CRC16(‘user-profile:1234’) mod 16384 | 15990
user-session:1234 | CRC16(‘user-session:1234’) mod 16384 | 2963
user-profile:5678 | CRC16(‘user-profile:5678’) mod 16384 | 9487
user-session:5678 | CRC16(‘user-session:5678’) mod 16384 | 4330
user-profile:{1234} | CRC16(‘1234’) mod 16384 | 6025
user-session:{1234} | CRC16(‘1234’) mod 16384 | 6025
user-profile:{5678} | CRC16(‘5678’) mod 16384 | 3312
user-profile:{5678} | CRC16(‘5678’) mod 16384 | 3312

<br class="Apple-interchange-newline" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">
